"""
提示词模块初始化
"""

from .supervisor import SUPERVISOR_SYSTEM_PROMPT, SUPERVISOR_ROUTING_PROMPT
from .interviewer import INTERVIEWER_SYSTEM_PROMPT, STAR_ANALYSIS_PROMPT
from .chat import CHAT_SYSTEM_PROMPT

__all__ = [
    "SUPERVISOR_SYSTEM_PROMPT",
    "SUPERVISOR_ROUTING_PROMPT",
    "INTERVIEWER_SYSTEM_PROMPT",
    "STAR_ANALYSIS_PROMPT",
    "CHAT_SYSTEM_PROMPT",
]
